### ISSUE TITLE
У ClothingShoesBootsCombatFilled нереально тихий звук ходьбы

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/ss14-core#135]

**Comment by NairSark** [comment]
Can't reproduce. Everything seems okay.
На какой плитке тестили и почему вообще Filled версия именно?

**Comment by ThereDrD0** [comment]
> Can't reproduce. Everything seems okay. На какой плитке тестили и почему вообще Filled версия именно?

Походил по обычной серой плитке в них, звуки были нереально тихие. 
Филлед, потому что я из вв скопировал прототип. Хз, может быть это единичый случай?
