### ISSUE TITLE
Баги с лежанием

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/ss14-core#261]
# Неправильное положение при движении
Двигаясь лежа вниз и направо персонаж игруна обучается ползанию на спине

Вниз

![image](https://github.com/frosty-dev/ss14-core/assets/88589686/f103a19e-5feb-45d6-810e-29ebb68be2eb)

Направо

![image](https://github.com/frosty-dev/ss14-core/assets/88589686/dcee57b5-7fbf-457c-9945-121c55f4b8f6)

# Неправильное состояние после вставания со стула

1. Ложимся
2. Садимся на стул
3. Встаем по стула

Теперь персонаж стоит, но двигается со скоростью лежания.
Этот же баг возможен при любых баклах лежачего персонажа куда-либо.

**Comment by Aviu00** [comment]
Еще в клиенте нет звука падения, если ты ложишься (на сервере он есть). Также по тебе не попадают прожектайлы руны кипящей крови, гранат, турелей, враждебных мобов, отраженные прожектайлы, если ты лежишь.

**Comment by Aviu00** [comment]
Также лёжа можно поскользнуться, и всякие модификаторы скорости по типу скоростных ботинок влияют на скорость передвижения лёжа.

**Comment by Aviu00** [comment]
Еще надо что-то сделать с Z уровнями, чтобы нельзя было прятаться лёжа под трупами. И запретить летать на джетпаке лёжа.

**Comment by ThereDrD0** [comment]
Плюс баг 

![image](https://github.com/frosty-dev/ss14-core/assets/88589686/1fd7ba8b-bccf-40f3-9371-65bc5c7f6041)
