### ISSUE TITLE
МАГ, COMPLETE EDITION

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/ss14-core#339]
# Че надо сделать по магу

- [x] - Перевод прочтения свитка
- [x] - Снижение чтения свитка до 1 секунды
- [x] - Описание для каждого заклинания касательно того, что оно делает и что делают альтернативные методы каста. Описания можно подрезать с [нашей вики](https://js.ss14.su/ru/roles/wizard)
- [x] - Наш крутой спрайт для костюма мага. Ссылка на спрайты - [wizard (1).zip](https://github.com/user-attachments/files/15748105/wizard.1.zip)
- [x] - Метод для мага попасть на станцию используя свою магию. Например создать телепорт, который при вхождении создаст рандомный телепорт на станцию и после выплевывания мага закроется.

## КРИТИЧЕСКОЕ:

- [x] - Если привязанный реколом предмет удаляется, то сервер падает

## Дальше по магии
**Клунифай и мимифай:**

- [x] - Заклинание клунифая должно превращать цель не в обычного клоуна, а в cluwne, зеленого клоуна. Он ржет смешно
- [x] - Заклинанию клунифая и мимифая нужно сильно порезать кд, это ж пиздец
- [x] - У клувнефикации и мимификации слишком маленький радиус, надо побольше сделать

**Карты:**

- [x] - Для заклинания карт, которое разбрасывает карты в разные стороны нужно немного увеличить число карт
- [x] - Для лкмовского заклинания карт нужно сильно порезать кд
- [ ] - Для зажатия карт нужно найти какой-нибудь другой, бумажный звук.

**Форс:**

- [x] - У альтклик заклинания форса нужно сильно понизить кд
- [x] - У зажатого форса надо сильно порезать кд

**Стена:**

- [x] - Допилить кд, чтобы между пропажей стены и возможностью ее заново поставить было окно в 1 секунду

**Инстант реколл:**

- [x] - Нужен звук, когда предмет успешно связан с персонажем

**Остальное:**

- [x] - У фаербола нужно немного понизить кд
- [x] - У кнока нужно немного понизить кд
- [x] - Количество дыма от блинка нужно сильно порезать, в идеале, чтобы было рандомом от 1го тайла до 3 на 3
- [x] - У теслы надо сильно порезать дальность атаки по технике после зажатия, это пиздец
- [x] - ~~Убрать forcewall свиток на спавне мага, так как он повторяет функционал force свитка.~~

**Заклинания без мантии:**
Нужно сделать так, чтобы некоторые заклинания не требовали на маге мантию, это

- [x] - Рекол
- [x] - Карты
- [x] - Форс
- [x] - Клунифай
- [x] - Мимифай

### Дополнительные заклинания:

- [x] 1. **Дезинтегрирование(эй нах, гиб)**

> Заряжает вашу руку мерзкой энергией, которую можно использовать для взрыва жертв. Это заклинание проявляется в вашей руке и требует, чтобы вы коснулись своей цели, поэтому вы не сможете использовать его в наручниках или в оглушении.

- [x] 2. **Подмена сознания(майндсвап)**

> Позволяет заклинателю переключаться между телами с целью. Вы должны быть рядом с целью, в которую хотите перейти, после чего вы оба будете нокаутированы примерно на 15 секунд. Не работает на цели без игрока внутри. 

## Анти-магия:

- [ ] - Нуллрод священника должен полностью блокировать магию
- [ ] - Серебряный крестик должен уменьшать урон от магических заклинаний на 15%
- [ ] - Золотой крестик должен уменьшать урон от магических атак на 30%

Можно придумать какой-то другой метод крестикам помогать в защите от магии, но хотя бы что-то сделать нужно. По отзыву педалей маг очень сильный и робастный игрок не оставляет космонавтам шанса. Нужна контра магии в лице священных вещей и, возможно, технологий.

## Внешность мага:

Тело мага должно иметь свои особые параметры рандома, чтобы маг получался более магическим.

- [x] - Возраст мага должен быть 90-170 лет. Он же чертов маг
- [x] - Маг должен иметь обязательный рандомный седой цвет волос
- [x] - Маг обязательно должен иметь бороду из доступных бород
- [x] - Маг обязательно должен иметь любую прическу кроме избранных.
- [x] - Прототип для доступных бород мага
- [x] - Прототип для доступных причесок мага

## Архивы с магическими звуками:

1. [1 (2).zip](https://github.com/user-attachments/files/15748110/1.2.zip)
2. [1 (3).zip](https://github.com/user-attachments/files/15748111/1.3.zip)

### Ведение этой хуйни
- Когда педали дадут свой фидбек после теста магии я допишу его сюда. Done
- Я буду ставить галочки напротив выполенного

**Comment by Aviu00** [comment]
> Убрать forcewall свиток на спавне мага, так как он повторяет функционал force свитка

Там же 2 разных спелла, один стены делает, другой притягивает/отталкивает

**Comment by Aviu00** [comment]
> У заклинания реколла звук исчезновения предмета резко обрывается

Не особо понятно, у меня вроде все норм

**Comment by ThereDrD0** [comment]
> > Убрать forcewall свиток на спавне мага, так как он повторяет функционал force свитка
> 
> Там же 2 разных спелла, один стены делает, другой притягивает/отталкивает

Он разве не повторяет функционал форса? Когда я тестил, они делали одну и ту же магию.

**Comment by ThereDrD0** [comment]
> > У заклинания реколла звук исчезновения предмета резко обрывается
> 
> Не особо понятно, у меня вроде все норм

Возможно просто такой звук

**Comment by ThereDrD0** [comment]
Дополнил таски анти-магией

**Comment by ThereDrD0** [comment]
После релиза это все еще нужно делать

**Comment by ThereDrD0** [comment]
Осталась только антимагия, но ее не стоит добавлять, потому что маг и так слабый. Ему нужно больше заклинаний и фикс самовзрыва на фаерболе. Пока закрываю
