### ISSUE TITLE
Проект баффа СБ

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/ss14-core#472]
Сб требуются баффы для повышения контроля над ситуацией

# Таски

## Отредактировать прототипы

- [x] Поднять резине урон по стамине в полтора раза
- [x] Добавить всем щитам больше защиты от дизармов

### Станлок

- [x] Добавить возможность станлока станбатоном. Это должен быть компонент, который можно поставить на оружие вроде станбатона или прожектайл. Если ентити с этим компонентом наносит урон по стамине, то у цели сбрасывается таймер стана.
- [x] Если цель была оглушена каким-то мелким станом, вроде стана от флешки, то таймер должен сброситься до дефолтного времени.

### Гранатомет

- [x] Гранатомет для СБ, который можно зарядить только светошумыми или дымовыми гранатами. Как только граната выстреливает из гранатомета и приземляется, она должна сдетонировать спустя 0.3 секунды. 
- [x] Время детонации и вайтлист гранат должен задаваться в прототипе гранатомета.

## Хз че 

- [x] Возможность моментально ставить и поднимать щит.

**Comment by DVOniksWyvern** [comment]
Riot Smoke Grenade:

- [x] Убрать дыму блокирование обзора (сделать прозрачным)
- [x] Сменить дыму цвет на #B54B3B
- [x] Добавить дыму альфа-канал (186, либо так чтобы было видно тела под ним)
