### ISSUE TITLE
Смешное РнД

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/ss14-core#644]
Я хочу убрать аномалии и артефакты как отдельные айтемы или предметы. 

Артефактом станет 100 случайных предметов на начало раунда/несколько процентов от всех айтемов
Аномалией станет случайный статичный предмет на станции, не стена, не окно, не решетка и т.п. предметы, которые никогда не найдут игроки.

**Comment by wCATw** [comment]
Идея забавная. Мои предложения:
Переделать нынешний детектор аномалий в, к примеру, детектор электромагнитных волн (как в фазмофобии) и дать ему еще функционал поиска призраков (я про реву)? Не очень юзабельно против гостов я думаю, зато прикольно (хотя если против гостов трупиков тоже будет пикать, то будет мем).
А если аномалиям дать приколы призраков? Моргающий свет, отрыв плиток и проводки, т.д.

**Comment by ThereDrD0** [comment]
Сделано
